openapi: "3.0.0"
info:
  title: "Employee API Documentation"
  version: "1.0.0"
paths:
  /employees:
    get:
      description: "get list of employees"
      tags:
        - employees
      responses:
        '200':
          description: "successfully returned a list of employees"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employees'
        '500':
          description: "server error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
    post:
      description: "create a new employee"
      tags:
        - employees
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employees'
      responses:
        '200':
          description: "successfully created a new employee"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
  /employees/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
    get:
      description: "get employee by id"
      tags:
        - employees
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
    put:
      description: "update employee by id"
      tags:
        - employees
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employees'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
    delete:
      description: "delete employee by id"
      tags:
        - employees
      responses:
        '204':
          description: "OK"
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
  /positions:
    get:
      description: "get list of positions"
      tags:
        - positions
      responses:
        '200':
          description: "successfully returned a list of employees"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Positions'
    post:
      description: "create a new position"
      tags:
        - positions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Positions'
      responses:
        '200':
          description: "successfully created a new position"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Positions'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '500':
          description: "server error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
  /positions/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
    get:
      description: "get position by id"
      tags:
        - positions
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Positions'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
    put:
      description: "update position by id"
      tags:
        - positions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Positions'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Positions'
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
    delete:
      description: "delete position by id"
      tags:
        - positions
      responses:
        '204':
          description: "OK"
        '400':
          description: "invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        '404':
          description: "request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
components:
  schemas:
    Employees:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        position_id:
          type: string
          description: reference to the position's id
    Positions:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        salary:
          type: number
    ErrorDetail:
      type: object
      properties:
        message:
          type: string